Adds sigils translation, refs #6
wunsh/elixir-docs-ru pull request #11
Opened 2017-07-27 18:55 UTC by sobolevn

2017-07-28 11:41 UTC, rtrv requested changes

2017-07-28 11:41 UTC, rtrv commented on sigils.md
> +Самый часто-используемый сигил в Эликсире - сигил [регулярных выражений](https://en.wikipedia.org/wiki/Regular_Expressions): `~r`.
`часто используемый` раздельно

2017-07-28 11:41 UTC, rtrv commented on sigils.md
> +# Регулярное выражение, которое находит в строки "foo" или "bar":
в строкЕ

2017-07-28 11:41 UTC, rtrv commented on sigils.md
> +В добавок, двойная кавычка внутри двойной кавычки должна быть экранирована как `\"`, аналогично и одинарная кавычка внутри одинарной кавычки `\'`. Тем не менее, лучше изменить разделители, чем исполь
`Вдобавок` слитно

2017-07-28 12:33 UTC, sobolevn commented
Fixed, thanks!

2017-07-29 12:40 UTC, rtrv approved these changes

2017-07-29 12:41 UTC, merged