update GenServer
wunsh/elixir-docs-ru pull request #15
Opened 2017-08-27 08:24 UTC by Zabalkanskiy

2017-08-28 09:52 UTC, rtrv requested changes

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +{% include toc.html %}
Эту строку нужно убрать, у нас нет этого меню

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +{% include mix-otp-preface.html %}
Это тоже нужно убрать

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +В [предыдущей главе](/getting-started/mix-otp/agent.html) мы использовали агенты(agents) чтобы представить наши корзины(buckets). В первой главе мы указали имя каждой корзины, поэтому мы можем сделат
Перед открывающимися скобками должны быть пробелы

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Поскольку агенты процессы, каждая корзина имеет идентификатор процесса (PID), но не имеет названия. Мы узнали об регистрации имени [в главе Процессы](/getting-started/processes.html) и вы могли бы ре
Между "агенты" и "процессы" в начале нужно тире
"о регистрации" вместо "об"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +На практике скорее всего, вы достигнете предела максимального количества атомов для Виртуальной Машины Эрланга и  ваша система упадет в любом случае.
"скорее всего" выделяется запятыми с обеих сторон
"и ваша" два пробела, перед "и" нужна запятая

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Вместо того, чтобы злоупотреблять регистрацией имени объекта, мы создадим процесс регистрации, который содержит карту(map), которая связывает имя корзины с процессом корзины.
мэп мы вроде договаривались не переводить, а транслитерировать, точно не помню, в какой главе. Имхо лучше оставить просто транслитерацию, термин понятный

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Регистрация должна гарантировать, что словарь постоянно обновляется. Например, если один из процессов падает из за ошибки в реестре вы должны очистить словарь для того, чтобы избежать обслуживания ус
"из-за" с дефисом
Запятая перед "вы должны"
"В Эликсире"
"мы описываем это тем, что реестр должен..." не совсем понял суть предложения, вероятно, не "описываем", а "обосновываем"?

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Мы будем использовать [GenServer](https://hexdocs.pm/elixir/GenServer.html) для создания реестра процессов, который может следить за корзиной процессов. GenServer обеспечивает промышленную мощь функц
Запятая перед "функциональность"
"в Эликсире"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +В GenServer состоит из двух частей: клиентского API и вызовов сервера. Вы можете либо объединить обе части в один модуль, или вы можете разделить их на клиентский модуль и модуль сервера. Клиент и се
"В GenServer состоит из двух частей" предлог "В" наверное лишний
Лучше использовать два раза "либо", или два раза "или", не смешивая

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Первая функция `start_link/3`, которая запускает GenServer передает три аргумента:
Запятая перед "передает"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Есть два типа запросов, которые вы можете отправить GenServer: синхронные вызовы(calls) и асинхронные вызовы(casts). Если вызовы являются синхронными сервер **должен** отправить ответ на такие запрос
Запятая перед "сервер должен"
Запятая перед "сервер не посылает"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Следующие две функции, `lookup/2` и `create/2` несут ответственность за отправку этих запросов к серверу. В данном случае, мы воспользовались `{:lookup, name}` и `{:create, name}` соответственно. Зап
Запятая перед "несут ответственность"
"Запрос часто указывается в качестве кортежей, как наши, для того, чтобы обеспечить более чем один “аргумент” в том, что первый слот аргумент" не понял предложение. Если там сложности с переводом, можно кинуть исходник в комменты, подумаем вместе.
Запятая перед "используют первый"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
После "На стороне сервера" не нужна запятая
Я у себя не переводил "коллбэки". @jarosluv @sobolevn ваше мнение, переводить или транслитерировать, "коллбэк" или "обратный вызов"?

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
Запятая после "являются необязательными"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Первый это `init/1` обратный вызов, который получает второй аргумент `GenServer.start_link/3` и возвращает `{:ok, state}` , где состояние представляет собой новую карту(map). Мы уже можем заметить, ч
"Первый - это" нужно тире, запятая после "init/1"
" , где состояние" перед запятой лишний пробел
карту -> мэп
"выпл в клиенте" опечатка

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Для `call/2` запросов, мы реализуем обратный вызов `handle_call/3`, который получает `request`, процесс от которого мы получили запрос (`_from`), и текущее состояние сервера (`names`). В handle_call/
"Для `call/2` запросов, мы реализуем" не нужна запятая
"получает `request`, процесс от которого мы получили запрос (`_from`), и текущее состояние сервера (`names`)" нужна запятая перед "от которого" и не нужна перед "и текущее"
"handle_call/3" не выделен в кавычки
"Первый элемент кортежа, `:reply`" уточнения, как `:reply` в данном предложении, выделяются запятыми с обеих сторон. Либо не выделяются вообще, если это часть подлежащего и не является уточнением.
"Второй Элемент" элемент с маленькой
"`reply` , это то" тут нужно тире вместо запятой
"втретий" опечатка
"`new_state`" - уточнение, запятые. Вообще по правилам там должно быть "третий, `new_state`, - это новое состояние сервера." Довольно дикая конструкция, но вполне допустимая

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Для `cast/2` запросов, мы реализуем обратный вызов `handle_cast/2`, который получает `request` и текущее состояние сервера (`names`). В `handle_cast/2` обратный вызов возвращает кортеж в формате {:no
"запросов, мы реализуем" не нужна запятая
"{:noreply, new_state}" завернуть бы в кавычки `{:noreply, new_state}`

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Есть и другие форматы кортежей для `handle_call/3` и `handle_cast/2` которые обратные вызовы могут возвратить. Так же есть и другие обратные вызовы,  такие как `terminate/2` и `code_change/3`  мы мог
"`handle_cast/2` которые" запятая перед "которые"
"вызовы,  такие как" два пробела
"`code_change/3`  мы могли" тоже два пробела и не хватает запятой перед "мы"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Теперь, давайте напишем несколько тестов, чтобы гарантировать что наш GenServer работает, как ожидалось.
После "Теперь" не нужна запятая
Запятая перед "что наш"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Нам не нужно явно закрыть реестр, потому что он будет получать сигнал `:shutdown`, когда наш тест заканчивается. При этом такое решение хорошо для тестов, если есть необходимость остановить `GenServe
"закрыть" -> "закрывать"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Наш реестр это почти готов. Единственный оставшийся вопрос заключается в том, что реестр может стать неактуальным, если корзина останавливается или падает. Давайте добавим тест `KV.RegistryTest`, кот
"Наш реестр это почти готов" можно убрать "это"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Для того, чтобы исправить эту ошибку, нам нужно зарегистровать монитор когда корзина создается. Как только мы установим монитор, реестр будет получать уведомления каждый раз, когда корзина заканчивае
"монитор когда корзина создается" запятая перед "когда"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Давайте переопределим коллбэки сервера, чтобы исправить баг и пройдем тест. Вопервых, мы изменим состояние GenServer используя два словаря: один, будет содержать `name ‐> pid` и другой, содержит `ref
"Во-первых" через дефис
"один, будет содержать" не нужна запятая. Вообще там лучше написать, например: "один будет содержать `name ‐> pid`, а другой - `ref ‐> name`"
Тут также актуален вопрос "коллбэки" или "обратные вызовы"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Заметим, что нам удалось значительно изменить реализацию сервера, без изменения каких либо API клиента. Это одно из преимуществ четкого разделения на серверную и клиентскую части.
"сервера, без изменения" не нужна запятая

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Наконец, в отличие от других обратных вызовов, мы определили положение “поймать-все” для функции `handle_info/2` которая удаляет любые подозрительные сообщения. Чтобы понять почему мы это сделали, да
"Чтобы понять почему" запятая перед "почему"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +До сих пор мы воспользовались тремя коллбэками: `handle_call/3`, `handle_cast/2` и `handle_info/2`. Вот что мы должны учитывать при
В конце этой строки перевод каретки лишний
"Вот, что мы должны" нужна запятая

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +2. `handle_cast/2` должен быть использован для асинхронных запросов, когда ты не заботишься об ответе. Бросок не дает гарантии что сервер получил сообщение и, по этой причине, его следует использоват
"которую мы определили в этой главе должна" запятая перед "должна"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +3. `handle_info/2` должен использоваться для всех других сообщений, которые сервер может получать и не передаются через `GenServer.call/2` или `GenServer.cast/2`, включая регулярные сообщения `send/2
"`:DOWN` как" тут тире перед "как", подлежащее и сказуемое - существительные

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Ссылки двунаправлены. Если вы связываете два процесса и один из них выйдет из строя, другая сторона тоже выйдет из строя (если только это не улавливает флаг trapping exits true). Монитор является одн
"два процесса и один из них" запятая перед "и"
"если только это не улавливает флаг trapping exits true" -> "если только не установлен флаг trapping exits true"
"мониторьте за процессами" -> "мониторьте процессы"

2017-08-28 09:52 UTC, rtrv commented on mix-otp/genserver.md
> +Это плохая идея, так как мы не хотим, чтобы реестр падал при сбое корзины! Мы обычно избегаем непосредственного создания новых процессов, вместо этого мы делегируем эту ответственность супервизорам.
"Настолько" с маленькой буквы
"ОТП" ранее было русскими, тут "OTP". Думаю, стоит везде использовать один вариант, и в случае кириллицы расшифровку также давать на русском, "открытая телекоммуникационная платформа"

2017-08-28 10:09 UTC, sobolevn commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
я за "обратный вызов", мы все термины переводим.

2017-08-28 10:09 UTC, sobolevn commented
@rtrv титаническая работа!

2017-08-28 10:19 UTC, rtrv commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
@sobolevn что насчёт "map"?

2017-08-28 10:20 UTC, rtrv commented on mix-otp/genserver.md
> +Это плохая идея, так как мы не хотим, чтобы реестр падал при сбое корзины! Мы обычно избегаем непосредственного создания новых процессов, вместо этого мы делегируем эту ответственность супервизорам.
"start_linkи" тут русская "и" затесалась

2017-08-28 10:21 UTC, sobolevn commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
словарь.

2017-08-28 10:34 UTC, rtrv commented on mix-otp/genserver.md
> +Это клиентский API. На стороне сервера, мы можем реализовать различные обратные вызовы, чтобы гарантировать инициализацию сервера, обработку запросов и прекращение работы сервера. Эти обратные вызовы
Да, действительно

2017-08-28 11:11 UTC, rtrv commented
@Zabalkanskiy спасибо за перевод, отличная работа, только мелочи поправить. Пожалуйста, отписывайся в #6 когда начинаешь перевод какого-то раздела, чтобы не возникло коллизий

2017-09-06 12:47 UTC, Zabalkanskiy commented on mix-otp/genserver.md
> +Следующие две функции, `lookup/2` и `create/2` несут ответственность за отправку этих запросов к серверу. В данном случае, мы воспользовались `{:lookup, name}` и `{:create, name}` соответственно. Зап
Requests are often specified as tuples, like this, in order to provide more than one "argument" in that first argument slot
перевел как то так
Запрос часто указывается в качестве кортежа, для того, чтобы обеспечить несколько “аргументов” в слоте.

2017-09-06 15:28 UTC, rtrv requested changes

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +В [предыдущей главе](/getting-started/mix-otp/agent.html) мы использовали агенты (agents) чтобы представить наши корзины (buckets). В первой главе мы указали имя каждой корзины, поэтому мы можем сдел
Вероятно забыл указать в прошлый раз, перед "чтобы" сразу после закрывающейся скобки нужна запятая

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +Поскольку - агенты процессы, каждая корзина имеет идентификатор процесса (PID), но не имеет названия. Мы узнали об регистрации имени [в главе Процессы](/getting-started/processes.html) и вы могли бы
Тут тире между "агенты" и "процессы"

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +Поскольку - агенты процессы, каждая корзина имеет идентификатор процесса (PID), но не имеет названия. Мы узнали об регистрации имени [в главе Процессы](/getting-started/processes.html) и вы могли бы
"об регистрации" -> "о регистрации"

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +Вместо того, чтобы злоупотреблять регистрацией имени объекта, мы создадим процесс регистрации, который содержит мэп, который связывает имя корзины с процессом корзины.
Обсуждали потом в комментах, что map всё-таки переводим как "словарь", дальше не пишу по этому поводу

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +Давайте переопределим коллбэки сервера, чтобы исправить баг и пройдем тест. Во-первых, мы изменим состояние GenServer используя два словаря: один будет содержать `name ‐> pid` а другой `ref ‐> name`.
"один будет содержать `name ‐> pid` а другой `ref ‐> name`" -> "один будет содержать `name ‐> pid`, а другой - `ref ‐> name`". Не хватает запятой и тире

2017-09-06 15:28 UTC, rtrv commented on mix-otp/genserver.md
> +Заметим, что нам удалось значительно изменить реализацию сервера без изменения каких либо API клиента. Это одно из преимуществ четкого разделения на серверную и клиентскую части.
"каких-либо" через дефис

2017-09-06 16:23 UTC, rtrv commented on mix-otp/genserver.md
> +Следующие две функции, `lookup/2` и `create/2` несут ответственность за отправку этих запросов к серверу. В данном случае, мы воспользовались `{:lookup, name}` и `{:create, name}` соответственно. Зап
Запросы часто заданы в виде кортежей, вроде этих, чтобы передать несколько аргументов на месте одного, первого аргумента

2017-09-08 13:50 UTC, rtrv approved these changes

2017-09-08 13:51 UTC, merged