Macros
wunsh/elixir-docs-ru pull request #18
Opened 2017-09-16 12:37 UTC by tyulpan

2017-09-16 12:46 UTC, tyulpan commented
Сегодня запушу ещё несколько частей

2017-09-16 19:31 UTC, rtrv requested changes

2017-09-16 19:31 UTC, rtrv commented on meta/macros.md
> +> В этой главе мы будет использовать файлы вместо запуска примеров кода в IEx. Всё потому, что эти примеры будут всего лишь в несколько строк кода, поэтому их ввод в IEx будет контрпродуктивным. След
Не хватает запятой после деепричастного оборота "записывая их в файл `macros.exs`"

2017-09-16 19:31 UTC, rtrv commented on meta/macros.md
> +Обратите внимание, что третьим элементом в маскирующей переменной является атом `Sample`, вместо `nil`, который отмечает переменную как поступающую из модуля `Sample`. Именно поэтому Эликсир рассматр
"следовательно" нужно выделить запятыми с обеих сторон

2017-09-16 19:31 UTC, rtrv commented on meta/macros.md
> +Многие функции в модуле `Macro` расчитывают на среду. Подробнее об этих функциях вы можете узнать в [документации модуля `Макрос`](https://hexdocs.pm/elixir/), а также узнать больше о среде компиляци
в случае с фразой "документации модуля `Макрос`" перевод названия модуля не нужен, следует вернуть туда "`Macro`"

2017-09-16 19:31 UTC, rtrv commented on meta/macros.md
> +## Частные макросы
Приватные по-моему будет более очевидно

2017-09-16 19:31 UTC, rtrv commented on meta/macros.md
> +* Макросы лексические: невозможно вводить код или макросы глобально. Чтобы использовать макрос, вам необходимо явно `потребовать` или `импортировать` модуль, определяющий макрос.
`require` и `import` - это ключевые слова из исходного кода, их не нужно переводить

2017-09-17 09:34 UTC, rtrv approved these changes

2017-09-17 09:35 UTC, merged