Update structs.md
wunsh/elixir-docs-ru pull request #2
Opened 2017-07-02 10:31 UTC by Zabalkanskiy

2017-07-02 10:32 UTC, Zabalkanskiy commented
update

2017-07-02 16:01 UTC, jarosluv commented
Спасибо за перевод!

Пожалуйста, добавьте `---` самой первой строкой, иначе файл не скомпилируется.

2017-07-02 17:27 UTC, jarosluv requested changes

2017-07-02 17:27 UTC, jarosluv commented on structs.md
> +title: Структуры
Необходимо добавить `---` первой строчкой.

2017-07-02 17:27 UTC, jarosluv commented on structs.md
> +Для определения структуры используется `defstruct` конструкция:
Лучше поменять местами на "конструкция`defstruct`"

2017-07-02 17:27 UTC, jarosluv commented on structs.md
> +```
Лучше добавить название языка в блоках кода здесь и в остальных местах.

"```elixir"

2017-07-02 17:27 UTC, jarosluv commented on structs.md
> +```
```elixir

2017-07-02 17:27 UTC, jarosluv commented on structs.md
> +Список ключевых слов, используемый при определении defstruct , определяет, какие поля будет иметь структура вместе со значениями по умолчанию.
Убрать пробел перед запятой.

2017-07-03 21:01 UTC, jarosluv commented on structs.md
> +Для определения структуры в `elixir` используется `defstruct` конструкция:
@Zabalkanskiy может быть я не совсем понятно выразился, но это не те правки, которые нужно было сделать.

1. Подзаголовок "Определение структур" нужно оставить как есть, это же прямой перевод.
2. Поменять местами слова "defstruct" и "конструкция" нужно в этом предложении, чтобы получилось
"Для определения структуры используется конструкция `defstruct`:".
3. Слово "elixir" нужно добавить в блоках кода, чтобы компилятор понимал, какую подсветку синтаксиса использовать. Если вы хотите добавить блок кода на языке Эликсир, нужно после трёх косых  обратных апострофов поставить название языка "elixir", чтобы получилось "```elixir".

Спасибо!

2017-07-04 20:28 UTC, jarosluv approved these changes

2017-07-04 20:28 UTC, merged