translate introduction-to-mix
wunsh/elixir-docs-ru pull request #5
Opened 2017-07-09 08:47 UTC by Zabalkanskiy

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Приложение работает в качестве распределенного хранилища ключ-значение(key-value). Мы собираемся организовать пары ключзначение в buckets(перевод ведра) и распространять эти buckets по нескольким узл
Не хватает пары дефиса и пробела: "ключзначение" и "построимпростой". Перед союзом "а" нет пробела

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +* ***ExUnit*** is a test-unit based framework that ships with Elixir;
Осталась оригинальная строка

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +* ***ExUnit*** framework поставляемый с `elixir` который позволяет тестировать(test-unit) приложение;
***ExUnit*** - фрэймворк для модульного тестирования, который поставляется вместе с Эликсиром.

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +>Примечание: это руководство требует elixir v1.2.0 или более поздней версии. Вы можете проверить свою версию `elixir` введя в терминале `elixir ‐‐version` и установить более свежую версию, если требу
Деепричастный оборот "введя в терминале `elixir ‐‐version`" следует выделить запятыми с обеих сторон

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +При установке Elixir, кроме получения `elixir` , `elixirc` и `iex` исполняемых файлов, вы также получаете исполняемый Elixir сценарий `mix`.
Лишний пробел после `elixir`. 
"кроме получения `elixir` , `elixirc` и `iex` исполняемых файлов" звучит на мой вкус как прямой перевод гуглотранслэйта, порядок слов в предложении явно с английского. "кроме получения исполняемых файлов `elixir`, `elixirc` и `iex`" было бы лучше.

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Давайте создадим наш первый проект с помощью вызова `mix new` из командной строки. Мы передадим проект имя в качестве аргумента ( `kv` в данном случае), и скажем Mix, что наш главный модуль должен со
"проект имя", наверное, "имя проекта"
Лишний пробел после открывающейся скобки

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +> Примечание: Mix представляет собой исполняемый Elixir. Это означает, что для работы `mix` , вы должны иметь Elixir исполняемый в вашей перменной PATH. Если у вас его нет в PATH, вы можете запустить
"исполняемый Эликсир", во втором упоминании обратный порядок слов
"перЕменной", опечатка
Запятая перед "используя"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +> Обратите внимание, что вы также можете выполнить любой скрипт в вашем пути(PATH) из Elixir с помощью опции -S:
Обратите внимание, что директория Эликсира находится в переменной PATH, и вы также можете выполнить любой скрипт с помощью опции -S:

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +> При использовании -S,`elixir` находит сценарий, где бы он не находился в вашем  пути(PATH) и выполняет его.
"в вашем пути(PATH)" -> "в переменной PATH"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Файл `mix.exs` был сгенерирован внутри нашей новой папке проекта (`kv`) и его основной задачей является настроить наш проект. Давайте взглянем на него (комментарии удалены):
"папкИ"
А зачем комментарии удалены?

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +`mix.exs` определяет две открытые функции: `project` , которая возвращает конфигурацию пректа, определяя параметры такие как имя проекта , версию приложения, версию языка `elixir`, и `application` ,
"прОекта"
Запятая перед "такие как"
Пара лишних пробелов перед запятыми

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +В `mix.exs` также представлена закрытая функция deps , которая вызывается из функции `project`, которая определяет зависимости нашего проекта. Определение deps как отдельной функции не является обяза
Название функции deps стоит заключить в кавычки: `deps`

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Mix также создает файл в lib/kv.ex простой модуль определения:
Не понятен смысл этой строки, можно оригинал или исправить?

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Файл `lib/kv.ex` был скомпилирован, манифест приложения `kv.app` был создан и все протоколы были объединены, как описано в руководстве по началу работы(смотри protocols). Все артефакты компиляции пом
Пробел перед открывающейся скобкой, на протоколы лучше будет сделать ссылку
Лишний пробел после `_build`
"в mix.exs файле" -> "в файле mix.exs"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Mix также создает соответствующие структуры для выполнения  тестов нашего проекта. Mix проекты, как правило, следуют Конвенции наличия `<filename>_test.exs` файла в директории `test` для каждого файл
"для выполнения  тестов" - двойной пробел
Запятая перед "соответствующий"
"Он не делает много на данный момент" -> "Пока он почти ничего не делает", например

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +1. тестовый файл это файл сценария ( `.exs` ) Elixir. Это удобное соглашение, потому что нам не нужно компилировать тестовые файлы перед их запуском;
Тире перед "это"
Elixir -> Эликсира

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +2. мы определяем тестовый модуль по имени `KVTest` , используем [`ExUnit.Case`] (https://hexdocs.pm/ex_unit/ExUnit.Case.html) для введения(inject) API тестирования  и определяем простой тест, с помощ
Перед "с помощью" запятая не нужна

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Обратите внимание, что при запуске `mix test` , Mix компилирует исходные файлы и генерирует  файл приложения еще раз. Это происходит потому, что Mix поддерживает несколько окружений(environments), ко
После `mix test` лишний пробел, после "генерирует" - двойной.
"Это происходит потому, что" -> "Это происходит, потому что". Составной союз запятая не ставится внутри, только перед ним.

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Для каждого сбоя, ExUnit печатает подробный отчет, содержащий  имя теста, причину падения, непрошедший успешно код, и значения выражения для левой стороны (lhs) и правоы стороны (rhs) для `==` операт
"правоЙ", опечатка

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Наконец, трассировка стека во время падения(failure), дает информацию о тесте и часто о месте падения которое было создано в исходных файлах.
Лишняя запятая перед "дает"
Не хватает запятой перед "которое"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +* `:dev` - в которой Mix задания(tasks) (как `compile` ) запускаются по умолчанию
Лишний пробел перед закрывающейся скобкой

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +При компиляции исходного кода, Elixir собирает артефакты в каталог `_build` . Однако, во многих случаях, чтобы избежать ненужного копирования, Elixir будет создать системные ссылки filesystem links)
Elixir -> Эликсир
Не понятно, откуда закрывающаяся скобка после "links"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Аналогично, при значении  :start_permanent True функция запускает приложение в режиме постоянной работы, что означает, что Erlang VM рухнет, если ваше древо надзора(supervision tree) приложения выклю
Двойной пробел после "при значении"
"при установленном в True значении :start_permanent, функция..."

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Mix это инструмент построения и он не всегда будет доступен в продакшн, особенно если ваша команда использует явные шаги построения приложений. Поэтому рекомендуется использовать `Mix.env` только в ф
Тире перед "это" в самом начале
Запятая после "построения"
"построения" -> "сборки"

2017-07-09 12:34 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +вызывая `mix help TASK`.
Лишний перевод каретки

2017-07-09 16:26 UTC, Zabalkanskiy commented
Спасибо за замечания исправлю

2017-07-11 18:31 UTC, Zabalkanskiy commented on mix-otp/introduction-to-mix.md
> +Файл `mix.exs` был сгенерирован внутри нашей новой папке проекта (`kv`) и его основной задачей является настроить наш проект. Давайте взглянем на него (комментарии удалены):
так в руководстве написано
A file named mix.exs was generated inside our new project folder (kv) and its main responsibility is to configure our project. Let's take a look at it (comments removed):

2017-07-11 18:36 UTC, Zabalkanskiy commented on mix-otp/introduction-to-mix.md
> +Mix также создает файл в lib/kv.ex простой модуль определения:
Mix also generates a file at lib/kv.ex with a simple module definition:
 как то так перевести можно ?
Mix также создает в файле lib/kv.ex простой модуль определения:

2017-07-12 10:31 UTC, jarosluv commented on mix-otp/introduction-to-mix.md
> +Mix также создает файл в lib/kv.ex простой модуль определения:
@Zabalkanskiy

Думаю, как-то так можно перевести:
```
Mix также создает файл `lib/kv.ex`, в котором просто определяется модуль:
```

2017-07-12 14:36 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Файл `mix.exs` был сгенерирован внутри нашей новой папке проекта (`kv`) и его основной задачей является настроить наш проект. Давайте взглянем на него (комментарии удалены):
Понял, тогда вопрос закрыт

2017-07-13 07:43 UTC, rtrv requested changes
@Zabalkanskiy по мелким замечаниям и вопросам к текстам у меня всё, после этих правок можно мержить.
Сейчас в реквесте два перевода по разным темам, в последствии лучше в таких ситуациях делать два PR, чтобы в каждом контекстом был только один конкретный файл и неразрешенные вопросы по одному не мешали мержу другого

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Приложение работает в качестве распределенного хранилища ключ-значение(key-value). Мы собираемся организовать пары ключ-значение в buckets(перевод ведра) и распространять эти buckets по нескольким уз
Есть более мягкий вариант перевода buckets - корзины. Полагаю, при первом упоминании можно указать в скобках оригинальное слово/выражение, в последующих достаточно переведённого. Как в случае с ключ-значение и узлами в этом же абзаце.

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +>Полный код для этого Гайда вы можете найти в [репозитории](https://github.com/josevalim/kv_umbrella)
Гайда - руководства?

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +При установке Elixir, кроме получения исполняемых файлов `elixir`, `elixirc` и `iex`, вы также получаете исполняемый Elixir сценарий `mix`.
При установке Эликсира, ... исполняемый Эликсир

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +> Примечание: Mix представляет собой исполняемый Elixir. Это означает, что для работы `mix` , вы должны иметь его в вашей переменной PATH. Если у вас его нет в PATH, вы можете запустить его из сценар
исполняемый Эликсир

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Mix также создает в файле lib/kv.ex простой модуль определения:
"module defenition" в оригинале? Полагаю, имели ввиду "простое определение модуля"

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +При компиляции исходного кода, Elixir собирает артефакты в каталог `_build`. Однако, во многих случаях, чтобы избежать ненужного копирования, Elixir будет создать системные ссылки filesystem links из
Эликсир собирает ... Эликсир будет

2017-07-13 07:43 UTC, rtrv commented on mix-otp/introduction-to-mix.md
> +Аналогично, при установленном в True значении :start_permanent, функция запускает приложение в режиме постоянной работы, что означает, что Erlang VM рухнет, если ваше древо надзора(supervision tree)
Erlang VM - виртуальная машина Эрланга

2017-07-14 14:17 UTC, rtrv commented
LGTM. @jarosluv merge it if you have no remarks

2017-07-15 20:42 UTC, merged

2017-07-15 20:48 UTC, jarosluv commented
@Zabalkanskiy @rtrv Guys, thanks for your work!

@Zabalkanskiy You make pull requests right, but for better joint work experience you need to update your master branch before start to work on new issue and create separate branch for it.