translate agents
wunsh/elixir-docs-ru pull request #9
Opened 2017-07-23 10:21 UTC by Zabalkanskiy

2017-07-25 11:40 UTC, rtrv requested changes

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +layout: getting-started
Вот эту строку нужно удалить

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +В этой главе мы будем создавать модуль с именем `KV.Bucket`. Этот модуль будет отвечать за хранение основных значений таким образом, что позволяет им быть прочитанными и измененными другими процессам
позволяет -> позволит

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Если вы пропустили Getting Started guide или читали его давно, обязательно перечитайте главу [Processes]. Мы будем использовать ее в качестве отправной точки.
Ссылки в скобках на Processes не хватает
Надо подумать над адекватным переводом "getting started guide"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +## проблема состояния
С большой буквы

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Эликсир это иммутабельный(immutable)  язык, в котором нет ничего общего по умолчанию. Если мы хотим сохранять состояние, создавать buckets, записывать и читать значения из нескольких мест, у нас есть
"(immutable)  язык" - двойной пробел
"нет ничего общего по умолчанию" - не понятно, что имеется ввиду. В исходнике было "shared"?
С `buckets` надо что-то думать тоже. Я их "корзинами" переводил, но это, пожалуй, не то.
"в Эликсир" -> "в Эликсире"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Мы уже говорили о процессах, а <abbr title="Erlang Term Storage">ЕТС</abbr> мы будем изучать далее в этом руководстве. Когда дело доходит до процессов, мы редко используем собственные реализации, вме
"в Эликсир" -> "в Эликсире"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +* [GenServer](https://hexdocs.pm/elixir/GenServer.html) - “Универсальный сервер”("Generic server") (процессы), который инкапсулирует состояние, обеспечивает синхронные и асинхронные вызововы, поддерж
"вызововы"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Давайте реализуем наш `KV.Bucket` используя агентов. Прежде чем приступить к выполнению, давайте сначала напишем несколько тестов. Сначала создадим файл в `test/kv/bucket_test.exs` (вспомните `.exs`
Запятая перед "используя" в первом предложении
"Сначала" в двух соседних предложениях. В последнем можно его в принципе опустить

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Наш первый тест запускает новый `KV.Bucket` и выполняет `get/2` и `put/3` операции в нем, утверждая, результат. Нам не надо явно остонавливать агента, потому что он связан с процессом тестирования и
"утверждая, результат" -> "с утверждением ожидаемых результатов" и запятая перед этим после "в нём" будет не нужна

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Наш новый тест должен упасть независимо от включенного или выключеного параметра `async: true`, передаваемого в `ExUnit.Case` так как, функциональность не реализована в тестируемом модуле.
Перед "так как" нужна запятая, а после не нужна

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Для того, чтобы устранить сбой теста, давайте создадим файл `lib/kv/bucket.ex`.  попробуйте написать реализацию модуля `KV.Bucket` самостоятельно, используя агентов, прежде чем заглядывать в код пред
До этого было "тест должен упасть", поэтому тут скорее "сбой" -> "падение"
"Попробуйте" с большой буквы, перед ним два пробела
"используя агентЫ"
Запятая перед "представленный

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Мы используем карту(map), чтобы сохранить наши ключи и значения. Об операторе Захвата `&`, вы можете почитать в [введении в руководство](/getting-started/modules-and-functions.html#function-capturing
Мэпы не переводим, общепринятый термин-калька.
"Захвата" можно и с маленькой
Перед "вы можете" не нужна запятая
"введении в руководство"? Введение скорее в руководстве, а не в руководство. Полагаю, тут бы больше подошел какой-то менее точный, но более понятный перевод

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +## Настройка тестов ответы(callbacks) ExUnit
Коллбэки тоже можно не переводить, а оставить калькой

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Прежде чем двигаться дальше и добавлять новую функциональность для `KV.Bucket`, давайте поговорим об обратных вызовах ExUnit. Как вы можете ожидать, все тесты `KV.Bucket` затребуют корзину, чтобы быт
обратные вызовы -> коллбэки
"Как вы можете ожидать, все тесты `KV.Bucket` затребуют корзину" звучит странно и не понятно.

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Давайте перепишем тест кейс используя обратные вызовы:
коллбэки отсюда и далее не упоминаю

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Получать значение и обновлять состояние агента позволяет один вызов функции `Agent.get_and_update/2`. Давайте реализуем `KV.Bucket.delete/2` функцию, которая удаляет ключ из корзины, возвращая его те
Полагаю, в исходнике было "one function call", в переводе стоит опустить "один"
"`KV.Bucket.delete/2` функцию" -> "функцию `KV.Bucket.delete/2`"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Теперь это ваша очередь, чтобы написать тест на функциональность выше! Кроме того, обязательно изучите документацию к модулю [`Agent`](https://hexdocs.pm/elixir/Agent.html), чтобы узнать больше о них
"Теперь это ваша очередь" без "это"
"на функциональность выше" -> "для этой функциональности"
"узнать больше о них" -> "узнать о них больше"

2017-07-25 11:40 UTC, rtrv commented on mix-otp/agent.md
> +Это различие имеет важное значение. Если есть дорогостоящие действия, вы должны рассмотреть, где лучше выполнить эти действия на клиенте или на сервере. Например:
Запятая перед "на клиенте"

2017-07-29 11:33 UTC, Zabalkanskiy commented on mix-otp/agent.md
> +Мы используем карту(map), чтобы сохранить наши ключи и значения. Об операторе Захвата `&`, вы можете почитать в [введении в руководство](/getting-started/modules-and-functions.html#function-capturing
the Getting Started guide Можно как руководство перевести?

2017-07-29 11:34 UTC, Zabalkanskiy commented on mix-otp/agent.md
> +Эликсир это иммутабельный(immutable)  язык, в котором нет ничего общего по умолчанию. Если мы хотим сохранять состояние, создавать buckets, записывать и читать значения из нескольких мест, у нас есть
Elixir is an immutable language where nothing is shared by default.  Оригинал
Эликсир это иммутабельный(immutable) язык, в котором нет ничего совместно используемого по умолчанию.

2017-07-29 12:47 UTC, rtrv requested changes

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +Если вы пропустили Руководство или читали его давно, обязательно перечитайте главу [Processes](https://github.com/wunsh/elixir-docs-ru/blob/master/processes.md). Мы будем использовать ее в качестве о
В таком случае непонятно, о каком именно руководстве идёт речь, наиболее прямой перевод - "руководство для начинающих"
Ссылка на processes.md должна быть относительной, т.к. файлы хостятся на хероку и ссылка должна вести на соседний страницу этого же ресурса, а не на исходник на гитхабе

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +## Настройка тестов callbacks ExUnit
Коллбэки просто транслитерируются, прямая калька на русский достаточно понятна

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +Прежде чем двигаться дальше и добавлять новую функциональность для `KV.Bucket`, давайте поговорим об callbacks ExUnit. Как вы можете ожидать, все тесты `KV.Bucket` затребуют корзину, чтобы быть запущ
об callbacks -> о коллбэках

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +Обратите внимание, что нам нужен механизм для передачи `bucket` pid из вызова теста. Мы делаем это с помощью тестового контекста. Когда мы возвращаем `{:ok, bucket: bucket}` из коллбэка, ExUnit объед
map -> мэп

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +Вы можете прочитать больше о ExUnit случаях в документации модуля [ExUnit.Case](https://hexdocs.pm/ex_unit/ExUnit.Case.html) и об колбэках в [ExUnit.Callbacks документации](https://hexdocs.pm/ex_unit
колбэках -> коллбэках

2017-07-29 12:47 UTC, rtrv commented on mix-otp/agent.md
> +Теперь ваша очередь, чтобы написать тест на функциональность выше! Кроме того, обязательно изучите документацию к модулю [`Agent`](https://hexdocs.pm/elixir/Agent.html), чтобы узнать больше о них бол
"больше о них больше" в конце, первое лишнее

2017-08-09 15:21 UTC, rtrv requested changes

2017-08-09 15:21 UTC, rtrv commented on mix-otp/agent.md
> +В следующей главе мы будем исследовать GenServers, где разделение между клиентами и серверами станет более очевидным.
Пустрой строки в конце не хватает, конфиг линтера добавили в репозиторий

2017-08-09 15:21 UTC, rtrv commented on mix-otp/agent.md
> +В следующей главе мы будем исследовать GenServers, где разделение между клиентами и серверами станет более очевидным.
В остальном не увидел больше ошибок. Линтером только пробежаться нужно

2017-08-12 13:32 UTC, Zabalkanskiy commented on mix-otp/agent.md
> +В следующей главе мы будем исследовать GenServers, где разделение между клиентами и серверами станет более очевидным.
подскажите как линтером пользоваться

2017-08-12 13:34 UTC, sobolevn commented on mix-otp/agent.md
> +В следующей главе мы будем исследовать GenServers, где разделение между клиентами и серверами станет более очевидным.
Я его еще не смерджил, может быть пока без линтера слить?

Я потом поправлю в любом случае все отклонения от стиля.

2017-08-13 13:38 UTC, Zabalkanskiy commented on mix-otp/agent.md
> +В следующей главе мы будем исследовать GenServers, где разделение между клиентами и серверами станет более очевидным.
хорошо если не против слейте

2017-08-13 15:38 UTC, merged